# Generated by Django 5.0.3 on 2024-03-16 07:43

import colorfield.fields
import django.core.validators
import django.db.models.deletion
import project_taxi.utilities
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('photo', models.ImageField(default='drivers/default_driver_image/png', upload_to='drivers/')),
                ('given_stars', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('groups', models.ManyToManyField(related_name='driver_groups', related_query_name='driver_group', to='auth.group')),
                ('user_permissions', models.ManyToManyField(related_name='driver_user_permissions', related_query_name='driver_user_permission', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
            bases=('shared.basemodel',),
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.CharField(default=project_taxi.utilities.set_id, editable=False, primary_key=True, serialize=False, unique=True)),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None)),
                ('photo', models.ImageField(default='cars/default_car_photo.jpg', upload_to='cars/')),
                ('number', models.CharField()),
                ('model', models.CharField()),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='drivers.driver')),
            ],
        ),
        migrations.CreateModel(
            name='DriverConfirmation',
            fields=[
                ('id', models.CharField(default=project_taxi.utilities.set_id, max_length=9, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=4)),
                ('expiration_time', models.DateTimeField(null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verify_codes', to='drivers.driver')),
            ],
        ),
        migrations.CreateModel(
            name='DriversLicense',
            fields=[
                ('id', models.CharField(default=project_taxi.utilities.set_id, editable=False, primary_key=True, serialize=False, unique=True)),
                ('series', models.CharField(default=0)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('photo', models.ImageField(default='drivers/default_driver_image.jpg', upload_to='drivers/licenses/')),
                ('category', models.CharField(choices=[('b', 'b'), ('bc', 'bc')], max_length=2)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_license', to='drivers.driver')),
            ],
        ),
    ]
