# Generated by Django 5.0.3 on 2024-03-23 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DriverStars',
        ),
    ]
