# Generated by Django 5.0.3 on 2024-03-23 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_delete_driverstars'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverStars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.DecimalField(decimal_places=2, max_digits=3)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_stars', to='drivers.driver')),
            ],
        ),
    ]
